before_script:
 - ln -s ./Makefile.standalone Makefile
 - which uncrustify
 - uname -a

stages:
 - build
 - test
 - release

buildlib:
 stage: build
 tags: 
  - shell
  - freebsd
 script:
  - make

verify_style9:
 stage: test
 tags: 
  - shell
  - freebsd
  - uncrustify
 script:
  - make checkstyle

doxygen:
 stage: release
 tags: 
  - shell
  - doxygen
 script:
  - make doxygen
 artifacts:
  paths:
   - stage/doxygen/

libifc:
 stage: release
 tags:
 - shell
 - freebsd
 script:
 - test -d stage/libifc
 artifacts:
  paths:
   - stage/libifc/

