before_script:
 - ln -s ./Makefile.standalone Makefile
 - uname -a

stages:
 - build
 - test
 - release

buildlib_with_clang:
 stage: build
 tags: 
  - shell
  - freebsd
  - clang
 script:
  - which clang
  - clang --version
  - make -f Makefile.ci buildwithclang
  - tree stage/libifc
 artifacts:
  name: "libifc-clang"
  paths:
   - stage/libifc/

buildlib_with_gcc:
 stage: build
 tags: 
  - shell
  - freebsd
  - gcc
 script:
  - which gcc
  - gcc --version
  - make -f Makefile.ci buildwithgcc
  - tree stage/libifc
 artifacts:
  name: "libifc-gcc"
  paths:
   - stage/libifc/

buildlib_in_base:
 stage: build
 tags:
  - shell
  - freebsd
 script:
  make -f Makefile.ci buildlibinbase

verify_style9:
 stage: test
 tags: 
  - shell
  - uncrustify
 script:
  - make -f Makefile.ci checkstyle

doxygen:
 stage: release
 tags: 
  - shell
  - doxygen
 script:
  - make doxygen
 artifacts:
  paths:
   - stage/doxygen/

freebsd_base_dist:
 stage: release
 tags:
  - shell
 script:
  - make -f Makefile.ci createfreebsdtree
  - tree stage/freebsdsrc
 artifacts:
  paths:
   - stage/freebsdsrc
