before_script:
 - ln -s ./Makefile.standalone Makefile
 - which uncrustify

stages:
 - build
 - test

buildstuff:
 stage: build
 script:
  - uname -a
  - make

verify_style9:
 stage: test
 script:
  - make checkstyle

